name: SparkPlugins CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [ 8, 11, 17 ]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Java ${{ matrix.java-version }}
      uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: ${{ matrix.java-version }}

    - name: Build using sbt for all Scala versions supported
      run: sbt +package
    - uses: actions/upload-artifact@v3
      with:
        name: SparkPlugins package scala 2.13
        path: target/scala-2.13/*.jar
    - uses: actions/upload-artifact@v3
      with:
        name: SparkPlugins package scala 2.12
        path: target/scala-2.12/*.jar
