name: SparkPlugins CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-24.04
    strategy:
      matrix:
        java-version: [ 11, 17 ]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java ${{ matrix.java-version }}
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: ${{ matrix.java-version }}
          cache: sbt
      - uses: sbt/setup-sbt@v1
        with:
          sbt-runner-version: 1.9.9

      - name: Upload SparkPlugins package for Scala 2.13
        if: matrix.java-version == '17'
        uses: actions/upload-artifact@v4
        with:
          name: SparkPlugins package scala 2.13
          path: target/scala-2.13/*.jar
        # This upload step is conditional on Java 17

      - name: Upload SparkPlugins package for Scala 2.12
        if: matrix.java-version == '11'
        uses: actions/upload-artifact@v4
        with:
          name: SparkPlugins package scala 2.12
          path: target/scala-2.12/*.jar
        # This upload step is conditional on Java 11
